# Generated by Django 3.2.8 on 2021-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('point', models.IntegerField(default=0)),
                ('kakao_id', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
