# Generated by Django 3.2.8 on 2021-10-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_phone_user_phone_number'),
        ('likes', '0001_initial'),
        ('reviews', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikereview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
        migrations.AddField(
            model_name='userlikereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='userlikemovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='userlikemovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
