# Generated by Django 3.2.8 on 2021-10-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movietheater',
            table='movie_theaters',
        ),
    ]
