# Generated by Django 3.2.8 on 2021-10-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_phone_user_phone_number'),
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('adult', models.IntegerField(null=True)),
                ('teenager', models.IntegerField(null=True)),
                ('kid', models.IntegerField(null=True)),
                ('movie_theater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theaters.movietheater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
