# Generated by Django 3.2.8 on 2021-10-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='movie_teather',
            new_name='movie_theater',
        ),
    ]
