# Generated by Django 3.2.8 on 2021-10-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ko_name', models.CharField(max_length=45)),
                ('eng_name', models.CharField(max_length=45)),
                ('release_date', models.DateField()),
                ('close_date', models.DateField()),
                ('screen_type', models.CharField(max_length=45)),
                ('director', models.CharField(max_length=45)),
                ('genre', models.CharField(max_length=45)),
                ('running_time', models.IntegerField()),
                ('age_rate', models.CharField(max_length=45)),
                ('actor', models.CharField(max_length=200)),
                ('total_audience', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_image_url', models.CharField(max_length=1000)),
                ('sub_image_url', models.CharField(max_length=1000)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
